name: CI
on:
  push:
    paths:
      - "**.zig"
  pull_request:
    branches: [main]
    paths:
      - "**.zig"
  schedule:
    - cron: "0 2 * * *"
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [0.12.0, 0.12.1, 0.13.0]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.version }}
      - uses: actions/checkout@v4
      - name: Run unit test
        run: zig build test
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
    - name: Verify formatting
      run: zig fmt .